#ifndef _ISLANDNAME_HPP_
#define _ISLANDNAME_HPP_
enum IslandName {
	ISLAND_NAME_1,
	ISLAND_NAME_2,
	ISLAND_NAME_3,
	ISLAND_NAME_4,
	ISLAND_NAME_5,
	ISLAND_NAME_6,
	ISLAND_NAME_7,
	ISLAND_NAME_8,
	ISLAND_NAME_9,
	ISLAND_NAME_10,
	ISLAND_NAME_11,
	ISLAND_NAME_12,
	ISLAND_NAME_13,
	ISLAND_NAME_14,
	ISLAND_NAME_15,
	ISLAND_NAME_16,
	ISLAND_NAME_17,
	ISLAND_NAME_18,
	ISLAND_NAME_19,
	ISLAND_NAME_20,
	ISLAND_NAME_21,
	ISLAND_NAME_22,
	ISLAND_NAME_23,
	ISLAND_NAME_24
};	
#endif 
